import EnergyPage from "../pages/energy/EnergyPage";
import FinancePage from "../pages/finance/FinancePage";
import MeteoDataGraphs from "./MeteoDataGraphs";
import MeteoDataTable from "./MeteoDataTable";
import images from "./../constants/images";
import { useSelector } from "react-redux";

const ReportPdf = ({ tableData, graphsData, projectData }) => {
  const { userInfo: user } = useSelector((state) => state.user);

  return (
    <div className="flex flex-col screen:h-0 screen:overflow-hidden">
      {/* Header */}
      <div className="flex flex-col items-center mb-10 text-light-hard">
        <img src={images.Logo} alt="logo" className="h-[50px] mb-4" />
        <div className="text-xl font-semibold">
          Report generated by: {user?.name}, {user?.email}
        </div>
        <div className="text-xl font-semibold">
          Report generated for: {projectData?.name}
        </div>
        <div className="text-xl font-semibold">
          Coordinates: {projectData?.latitude.toFixed(2)},{" "}
          {projectData?.longitude.toFixed(2)}
        </div>
      </div>
      {/* content */}
      <div className="w-full">
        <div className="text-3xl font-semibold mb-4">Meteo Data</div>
        <MeteoDataTable data={tableData} />
        <MeteoDataGraphs data={graphsData} />
        <div className="w-full mt-40">
          <EnergyPage />
          <FinancePage />
        </div>
      </div>
      <div className="">
        <img src={images.ThankYou} alt="thanks" />
      </div>
    </div>
  );
};
export default ReportPdf;
