import { useState } from "react";
import HomePageLayout from "../../components/HomePageLayout";

const FaqPage = () => {
  const [activeIndex, setActiveIndex] = useState(null);

  const toggleAccordion = (index) => {
    setActiveIndex(index === activeIndex ? null : index);
  };

  const accordionItems = [
    {
      question: "How does a solar rooftop system work?",
      answer: `A solar rooftop system works on the concept of conversion of sunlight into electricity. The phenomenon is known as the photovoltaic effect. When sunlight falls on the PV cells in a solar panel, the sunlight is converted into electricity. The generated power is DC current. An AC combiner box is used to convert that DC power into usable AC power. The generated AC electricity is fed into a bidirectional meter that supplies power to the house. It also exports excess power to the grid and imports power from the grid if electricity generated by the rooftop solar system is not enough to cover the daily requirement.`,
    },
    {
      question: `Why should I go solar?`,
      answer: `If you want to save money from the sun, Solar is the best investment for you. Solar allows you to save on your monthly electric bills plus it also allows you to save the planet by going green. Solar energy is a true form of renewable clean energy which leads to zero pollution (air, noise, land) and emits no greenhouse gases mitigating climate change.`,
    },
    {
      question: `Is solar power safe?`,
      answer: `Yes. The electricity produced by a solar power system is no different than the electricity you get from your electricity distribution company. The only difference is the source. Moreover, it is among the safest source of electricity consumption because it is neither hazardous nor does it release any toxic or harmful gases during production.`,
    },
    {
      question: `Do solar panels generate electricity even during monsoon and winter?`,
      answer: `Yes, Solar panels do produce electricity in cloudy or rainy weather with reduced efficiency. This fall in production is considered in the unit generation estimates provided for every project.`,
    },
    {
      question: `Does a rooftop solar PV generate power during a power failure?`,
      answer: `No, rooftop solar PV does not function or generate electricity during a blackout due to safety reasons. Since blackouts occur when the electricity grid is damaged. If a solar inverter was still feeding electricity into a damaged grid it would risk the safety of the people repairing the fault in the network. SolarSquare Energy provides the option of using a Li-ion storage battery with Solar power plants for areas which suffer from frequent power failures. This battery unit can store the excess electricity produced during the day and acts as a backup for any electricity requirement during night or in the event of a power failure.`,
    },
    {
      question: `What is the life of a rooftop solar system?`,
      answer: `The Solar Plant life is 25 years. The main components are solar panels and inverters. Solar panels have a warranty of 25 years and inverter warranty ranges from 5-12 years.`,
    },
  ];
  return (
    <HomePageLayout>
      <div className="w-3/4 mx-auto text-3xl mb-5 mt-16 font-bold">FAQ</div>
      <div
        id="accordion-collapse"
        data-accordion="collapse"
        className="w-3/4 mx-auto"
      >
        {accordionItems.map((item, index) => (
          <div key={index}>
            <h2 id={`accordion-collapse-heading-${index + 1}`}>
              <button
                type="button"
                className="flex items-center justify-between w-full p-5 font-semibold rtl:text-right text-dark-hard border border-gray-200 focus:ring-4 focus:ring-gray-200 hover:bg-gray-100 gap-3"
                data-accordion-target={`#accordion-collapse-body-${index + 1}`}
                aria-expanded={activeIndex === index}
                aria-controls={`accordion-collapse-body-${index + 1}`}
                onClick={() => toggleAccordion(index)}
              >
                <span>{item.question}</span>
                <svg
                  data-accordion-icon
                  className={`w-3 h-3 rotate-${
                    activeIndex === index ? "0" : "180"
                  } shrink-0`}
                  aria-hidden="true"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 10 6"
                >
                  <path
                    stroke="currentColor"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M9 5 5 1 1 5"
                  />
                </svg>
              </button>
            </h2>
            <div
              id={`accordion-collapse-body-${index + 1}`}
              className={`${activeIndex === index ? "" : "hidden"}`}
              aria-labelledby={`accordion-collapse-heading-${index + 1}`}
            >
              <div className="p-5 border border-b-0 border-gray-200">
                <p className="mb-2 text-dark-soft">{item.answer}</p>
              </div>
            </div>
          </div>
        ))}
      </div>
    </HomePageLayout>
  );
};
export default FaqPage;
